In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam

In [2]:
import os
import pandas as pd

dataframes = pd.DataFrame()

# base1 = pd.read_csv("D:\\CEDERJ\\2024.2\\tcc\\IVOptionPredictor\\projeto\\data\\iniciais\\strike_4a10_spot_3.5a12.2\\base_de_dados_1.csv")
# results1 = pd.read_csv("D:\\CEDERJ\\2024.2\\tcc\\IVOptionPredictor\\projeto\\data\\iniciais\\strike_4a10_spot_3.5a12.2\\result_1.csv")
        
# df_result_filtrado = results1[results1['0'].notna()]
# indices_to_keep = df_result_filtrado.index
# df_inputs_filtrado = base1.loc[indices_to_keep]
# df_filtrado = pd.concat([df_inputs_filtrado, df_result_filtrado], axis=1)
# dataframes = pd.concat([dataframes, df_filtrado], axis = 0)

base2 = pd.read_csv("D:\\CEDERJ\\2024.2\\tcc\\IVOptionPredictor\\projeto\\data\\iniciais\\strike_10a15_spot_8.5a17.2\\base_de_dados_2.csv")
results2 = pd.read_csv("D:\\CEDERJ\\2024.2\\tcc\\IVOptionPredictor\\projeto\\data\\iniciais\\strike_10a15_spot_8.5a17.2\\result_2.csv")
        
df_result_filtrado = results2[(results2['Result'].notna()) & (results2['Result'] != -1)]
indices_to_keep = df_result_filtrado.index
df_inputs_filtrado = base2.loc[indices_to_keep]
df_inputs_filtrado['Result'] = df_result_filtrado['Result']
# df_filtrado = pd.concat([dataframes, df_result_filtrado], axis=1)

dataframes = pd.concat([dataframes, df_inputs_filtrado], axis = 0)

# base3 = pd.read_csv("D:\\CEDERJ\\2024.2\\tcc\\IVOptionPredictor\\projeto\\data\\iniciais\\strike_15a20_spot_12.5a22.5\\base_de_dados_3.csv")
# results3 = pd.read_csv("D:\\CEDERJ\\2024.2\\tcc\\IVOptionPredictor\\projeto\\data\\iniciais\\strike_15a20_spot_12.5a22.5\\result_3.csv")
        
# df_result_filtrado = results3[(results3['Result'].notna()) & (results3['Result'] != -1)]
# df_result_filtrado_sem_invalidos = results3[results3['0'].notna()]
# indices_to_keep = df_result_filtrado.index
# df_inputs_filtrado = base3.loc[indices_to_keep]
# df_inputs_filtrado['Result'] = df_result_filtrado['Result']
# dataframes = pd.concat([dataframes, df_inputs_filtrado], axis = 0)

# print(dataframes.head())

# base4 = pd.read_csv("D:\\CEDERJ\\2024.2\\tcc\\IVOptionPredictor\\projeto\\data\\iniciais\\strike_20a25_spot_17.5a27.5\\base_de_dados_4.csv")
# results4 = pd.read_csv("D:\\CEDERJ\\2024.2\\tcc\\IVOptionPredictor\\projeto\\data\\iniciais\\strike_20a25_spot_17.5a27.5\\result_4.csv")
        
# df_result_filtrado = results4[results4['0'].notna()]
# indices_to_keep = df_result_filtrado.index
# df_inputs_filtrado = base4.loc[indices_to_keep]
# df_filtrado = pd.concat([df_inputs_filtrado, df_result_filtrado], axis=1)
# dataframes = pd.concat([dataframes, df_filtrado], axis = 0)

dataframes['CallPut'] = dataframes['CallPut'].replace({'call': 0, 'put': 1})
print(dataframes)

         Unnamed: 0  Strike  Maturity  Spot  TaxaDesconto  Premio  CallPut  \
0                 0    10.0       0.2   8.5          0.08    1.00        0   
2                 2    10.0       0.2   8.5          0.08    1.25        0   
4                 4    10.0       0.2   8.5          0.08    1.50        0   
5                 5    10.0       0.2   8.5          0.08    1.50        1   
6                 6    10.0       0.2   8.5          0.08    1.75        0   
...             ...     ...       ...   ...           ...     ...      ...   
2303995     2303995    14.9       0.9  17.2          0.10    4.25        1   
2303996     2303996    14.9       0.9  17.2          0.10    4.50        0   
2303997     2303997    14.9       0.9  17.2          0.10    4.50        1   
2303998     2303998    14.9       0.9  17.2          0.10    4.75        0   
2303999     2303999    14.9       0.9  17.2          0.10    4.75        1   

           Result  
0        0.976155  
2        1.141012  
4  

C:\Users\Public\Documents\Wondershare\CreatorTemp\ipykernel_19520\2829134534.py:47: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  dataframes['CallPut'] = dataframes['CallPut'].replace({'call': 0, 'put': 1})


In [14]:
print(dataframes.shape[0])
df_filtrado = dataframes[dataframes['TaxaDesconto'].isin([0.08, 0.09, 0.1])]
print(df_filtrado.shape[0])
df_filtrado = df_filtrado[df_filtrado['Maturity'].isin([0.2, 0.3, 0.4])]
print(df_filtrado.shape[0])
df_filtrado = df_filtrado[df_filtrado['CallPut'].isin([0])]
print(df_filtrado.shape[0])

df_filtrado = df_filtrado[(df_filtrado['Spot'] >= 9.5) & (df_filtrado['Spot'] <= 15.5)]
print(df_filtrado.shape[0])

dataframes = df_filtrado

1341925
805145
256525
127055
112619


In [5]:
import numpy as np
from sklearn.model_selection import train_test_split

# Separando as features e o alvo
X = dataframes[['Strike', 'Maturity', 'Spot', 'TaxaDesconto','Premio','CallPut']].values
y = dataframes['Result'].values

# Dividindo os dados em conjunto de treinamento e teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Normalizando os dados
# scaler = StandardScaler()
# X_train = scaler.fit_transform(X_train)
# X_test = scaler.transform(X_test)


In [6]:
print(y_train)

[1.06909289 0.67935139 0.86786096 ... 0.33472198 0.7823687  2.20447742]


In [20]:
print(len(X_train))
print(X_train.dtype)
print(len(X_test))
print(X_test.dtype)
print(len(y_train))
print(y_train.dtype)
print(len(y_test))
print(y_test.dtype)
print("###########################")

# print(np.isnan(X_train).any())  # Deve retornar False
# print(np.isinf(X_train).any())  # Deve retornar False

# print(np.isnan(X_test).any())  # Deve retornar False
# print(np.isinf(X_test).any())  # Deve retornar False
# print(np.isnan(y_train).any())  # Deve retornar False
# print(np.isinf(y_train).any())  # Deve retornar False
# print(np.isnan(y_test).any())  # Deve retornar False
# print(np.isinf(y_test).any())  # Deve retornar False

X_train = np.array(X_train, dtype=np.float32)
X_test = np.array(X_test, dtype=np.float32)
y_train = np.array(y_train, dtype=np.float32)
y_test = np.array(y_test, dtype=np.float32)

6983673
object
1745919
object
6983673
int64
1745919
int64
###########################


ValueError: could not convert string to float: 'call'

In [9]:
# Definindo a arquitetura da rede neural
model = Sequential()

# Camada de entrada com 4 neurônios (correspondendo aos 4 inputs)
model.add(Dense(30, input_dim=6, activation='relu'))

# Camada oculta com 32 neurônios
# model.add(Dense(32, activation='relu'))

# Camada oculta com 16 neurônios
# model.add(Dense(16, activation='relu'))

# Camada de saída com 1 neurônio (correspondendo à volatilidade implícita)
model.add(Dense(1, activation='linear'))

# Compilando o modelo
model.compile(optimizer=Adam(learning_rate=0.001), loss='mse')


d:\CEDERJ\2024.2\tcc\IVOptionPredictor\myenv\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [30]:
print(Y_train)

NameError: name 'Y_train' is not defined

In [10]:
scaler_X = StandardScaler()
X_train_scaled = scaler_X.fit_transform(X_train)

scaler_y = StandardScaler()
y_train_scaled = scaler_y.fit_transform(y_train.reshape(-1, 1))

# Ajustando o modelo com os dados normalizados
history = model.fit(X_train_scaled, y_train_scaled, epochs=1, validation_split=0.2)


26839/26839 ━━━━━━━━━━━━━━━━━━━━ 113s 4ms/step - loss: 0.0505 - val_loss: 0.0011


In [11]:
# Normalizando X_test
X_test_scaled = scaler_X.transform(X_test)

# Normalizando y_test para a avaliação
y_test_scaled = scaler_y.transform(y_test.reshape(-1, 1))

# Avaliando o desempenho do modelo no conjunto de teste
loss = model.evaluate(X_test_scaled, y_test_scaled)
print(f'Loss no conjunto de teste: {loss}')

# Fazendo previsões
y_pred_scaled = model.predict(X_test_scaled)

# Desnormalizando as previsões
y_pred = scaler_y.inverse_transform(y_pred_scaled)

8388/8388 ━━━━━━━━━━━━━━━━━━━━ 27s 3ms/step - loss: 0.0011
Loss no conjunto de teste: 0.0010939588537439704
8388/8388 ━━━━━━━━━━━━━━━━━━━━ 25s 3ms/step


In [13]:
X_new = X_test[:3]

y_pred = model.predict(X_new)

print(y_pred)

print(y_test[:3])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 183ms/step
[[-0.37951028]
 [-0.7070981 ]
 [-0.40410817]]
[0.75122208 1.03344043 0.71570995]
